#%RAML 1.0
---
title: CMS API
baseUri: http://localhost/api
version: 1.0

/posts:
    description: Danh sách những bài viết có trong database
    get:
        description: Lấy một list những bài viết.
        queryParameters:
            postTitle:
                description: "Sắp xếp theo tên được tìm kiếm"
                required: true
                minLength: 3
                type: string
                example: "Get L"
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "posts": |
                                [
                                    {
                                        "postId": "550e8400-e29b-41d4-a716-446655440000",
                                        "postTitle": "Get Lucky"
                                    },
                                    {
                                        "postId": "550e8400-e29b-41d4-a716-446655440111",
                                        "postTitle": "Loose yourself to dance"
                                    },
                                    {
                                        "postId": "550e8400-e29b-41d4-a716-446655440222",
                                        "postTitle": "Gio sorgio by Moroder"
                                    }
                                ]
                            }
    /{postId}:
        description: Lấy một bài Post theo Id
            get:
                description: lấy bài post theo Id  = {postId}
                responses:
                    200:
                        body:
                            application/json:
                                example: |
                                {
                                    "postId": "550e8400-e29b-41d4-a716-446655440000",
                                    "postTitle": "Get Lucky",
                                    "dateCreated": "6:07",
                                    "Content: "This is content of post",
                                    "artist": |
                                    {
                                        "artistId": "110e8300-e32b-41d4-a716-664400445500"
                                        "artistName": "Daft Punk",
                                    },
                                    "genre": |
                                    {
                                        "genreId": "183100e3-0e2b-4404-a716-66104d440550",
                                        "genreName": "Lean cooking",
                                    },
                                    "tags: |
                                    [
                                        {
                                            "tagId": "183100e3-0e2b-4404-a716-66104d440550"
                                            "tagName: "hot"
                                        },
                                        {
                                            "tagId": "110e8300-e32b-41d4-a716-664400445500"
                                            "tagName": "dinner"
                                        }
                                    ] 
                                }
                    404:
                        body:
                            application/json:
                                example: |
                                    {
                                        "message": "Post not found"
                                    }
    post:
        description: Tạo một bài Post
        body:
            application/json:
                example: |
                    {
                        "postId": "550e8400-e29b-41d4-a716-446655440000",
                        "postTitle": "Get Lucky",
                        "dateCreated": "6:07",
                        "Content: "This is content of post",
                        "artist": |
                            {
                                "artistId": "110e8300-e32b-41d4-a716-664400445500"
                            }
                        "genre": |
                            {
                                "genreId": "183100e3-0e2b-4404-a716-66104d440550"
                            }
                        "tag": |
                            {
                                "tagId": "110e8300-e32b-41d4-a716-664400445500"
                            }
                    }




