securedBy: oauth2
is: [ adminAuthorized, superAdminOrOwner ]

/{id}:
  get:
    description: Get detail information of a post
    responses:
      200:
        body:
          application/json:
            type: postDetail
            example: |
                                {
                                    "id": "550e8400-e29b-41d4-a716-446655440000",
                                    "title": "Get Lucky",
                                    "dateCreated": "6:07",
                                    "content: "This is content of post",
                                    "artist": |
                                    {
                                        "id": "110e8300-e32b-41d4-a716-664400445500"
                                    },
                                    "genre": |
                                    {
                                        "id": "183100e3-0e2b-4404-a716-66104d440550",
                                    },
                                    "tags: |
                                    [
                                        {
                                            "id": "183100e3-0e2b-4404-a716-66104d440550"
                                        },
                                        {
                                            "id": "110e8300-e32b-41d4-a716-664400445500"
                                        }
                                    ] 
                                }

  patch:
    description: Update post
    body:
      application/json:
        type: postSimple

    responses:
      200:
        body:
          application/json:
            type: postDetail
      412:
        body:
          application/json:
            type: object
            properties:
    delete:
        description: Delete a post
        responses:
            200:
                body:
                    application/json:
                        type: post
