#%RAML 1.0
---
title: CMS API
baseUri: http://localhost/api
version: 1.0

/securitySchemes:
  oauth2: !include oauth/oauth.raml

/traits:
  paged: !include traits/paged.raml
  adminAuthorized: !include traits/adminAuthorized.raml
  artistAuthorized: !include traits/superAdminAuthorized.raml

/admins:
  /: !include resources/admins/crud.raml
  /login: !include resources/admins/login.raml

/users:
  /: !include resources/users/curd.raml
  /signup: !include resources/users/signup.raml
  /login: !include resources/users/login.raml

/me: !include resources/users/me.raml

/tags:
  /: !include resources/tags/curd.raml


