securedBy: oauth2
is: [ adminAuthorized, superAdminOrOwner ]

get:
    description: List tags
    queryParameters:
            postTitle:
                description: 
                required: true
                minLength: 3
                type: string
    responses:
        200:
            body:
                application/json:
                    type: array
                    items: tag

/{id}:
  get:
    description: Get detail information of a tag
    responses:
      200:
        body:
          application/json:
            type: tagDetail

  patch:
    description: Update tag
    body:
      application/json:
        type: tagSimple

    responses:
      200:
        body:
          application/json:
            type: tagDetail
      412:
        body:
          application/json:
            type: object
            properties:
    delete:
        description: Delete a tag
        responses:
            200:
                body:
                    application/json:
                        type: tag
